# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20171121_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='meds_price',
            field=models.FloatField(max_length=10),
        ),
    ]
