# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171121_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cough_name', models.CharField(max_length=100)),
                ('cough_price', models.FloatField(max_length=10)),
                ('cough_image', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Medicine')),
            ],
        ),
    ]
