# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_cough'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='meds_type',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
