# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_medicine_meds_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flu_id', models.CharField(max_length=100)),
                ('flu_name', models.CharField(max_length=100)),
                ('flu_price', models.FloatField(max_length=10)),
                ('flu_image', models.CharField(max_length=100)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Medicine')),
            ],
        ),
        migrations.AddField(
            model_name='cough',
            name='cough_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
