# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20171122_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cough',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='flu',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='meds_type',
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_caution',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_description',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_direction',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_image',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_indication',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_ingredient',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_overview',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicine',
            name='meds_price',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cough',
        ),
        migrations.DeleteModel(
            name='Flu',
        ),
    ]
