# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20171123_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='meds_caution',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='meds_description',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='meds_direction',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='meds_indication',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='meds_ingredient',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='meds_overview',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supp_caution',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supp_description',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supp_direction',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supp_indication',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supp_ingredient',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='supp_overview',
        ),
    ]
