# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20171123_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_overview', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=500)),
                ('direction_use', models.CharField(max_length=500)),
                ('ingredients', models.CharField(max_length=500)),
                ('contra_indication', models.CharField(max_length=500)),
                ('caution', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PageSource',
            fields=[
                ('page_id', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', models.CharField(max_length=400)),
                ('page_name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SearchItem',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_price', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=300)),
                ('item_image', models.CharField(max_length=300)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.PageSource')),
            ],
        ),
        migrations.AddField(
            model_name='description',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.SearchItem'),
        ),
    ]
