# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20171126_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='item_link',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
    ]
