# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_searchitem_item_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
        migrations.DeleteModel(
            name='Supplement',
        ),
        migrations.AddField(
            model_name='searchitem',
            name='item_allergy',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
