# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20171204_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchitem',
            name='store_location',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
